### ISSUE TITLE
Mention __untagged__ in the README.md

### ISSUE THREAD

**Issue by souliane** [guludo/timewarrior-balance#1]
Thanks for this, it's useful!

Maybe you would like to add in the documentation that the config file can use `__untagged__` to allocate time without any tag.

Cheers,
Adrien

**Comment by guludo** [comment]
Hi @souliane!

I'm glad this it useful to you! 🙂

There is a mention in the README, in the bullet point that talks about `<tag>` (at the end of the introduction of https://github.com/guludo/timewarrior-balance#configuration-file),
